language: java
jdk:
  - openjdk8
  - openjdk11
branches:
  only:
    - master
before_install:
  - cp ./toolchains.xml ~/.m2/
install: mvn clean package -Ptravis -Dgpg.skip -Dmaven.test.skip=true
after_success:
  - mvn clean test jacoco:report coveralls:report