version: 2
jobs:
  build:

    working_directory: ~/JTuple
    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:

      - checkout
      - restore_cache:
          key: JTuple-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline


      - save_cache:
          paths:
            - ~/.m2
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}

      - run: mvn package

      - store_artifacts:
          path: target/JTuple-1.2.2-SNAPSHOT.jar